function config = getConfigEFLVM(dataname, model)
%
% Config file specifying all sampler and settings for running EFA and BPM
% models.
%

switch dataname
    case 'blockImages'
        switch model
            case 'efa'
                config = struct(...
                    'nSamples', 50, ...
                    'burnin', 10, ...
                    'nLeaps',  80, ...
                    'stepSize', 1e-5 , ...
                    'thin', 1, ...
                    'saveout', 1);
            
            case 'bpm'
                config = struct(...
                    'nSamples', 50, ...
                    'burnin', 10, ...
                    'nLeaps',  80, ...
                    'stepSize', 1e-5 , ...
                    'thin', 1, ...
                    'saveout', 0);
        end;
        
    case 'synth'
        switch model
            case 'efa'
                config = struct(...
                    'nSamples', 5000, ...
                    'burnin', 2500, ...
                    'nLeaps',  80, ...
                    'stepSize', 1e-3, ...
                    'thin', 1, ...
                    'saveout', 1, ...
                    'display', 1);
            otherwise
                error('====> Can only use method: efa, for data: %s',dataname);
        end;
        
    case 'bpmmodel'
        switch model
            case 'bpm'
                config = struct(...
                    'nSamples', 4000, ...
                    'burnin', 2000, ...
                    'nLeaps',  80, ...
                    'stepSize', 5e-3, ...
                    'thin', 1, ...
                    'saveout', 1);
            otherwise
                error('====> Can only use method: bpm, for data: %s',dataname);
        end;
        
    case 'votes'
        switch model
            case 'bpm'
                config = struct(...
                    'nSamples', 2000, ...
                    'burnin', 1000, ...
                    'nLeaps',  80, ...
                    'stepSize', 1e-3, ...
                    'thin', 1, ...
                    'saveout', 1);
                
            case 'efa'
                config = struct(...
                    'nSamples', 100, ...
                    'burnin', 50, ...
                    'nLeaps',  80, ...
                    'stepSize', 2e-3, ...
                    'thin', 1, ...
                    'saveout', 1);
        end;
        
    otherwise
        error('No config for data');
end;
